FROM wso2/wso2am:4.6.0

# Add MySQL connector for database connectivity
ADD --chown=wso2carbon:wso2 wso2/reposistory/components/lib/mysql-connector-j-8.0.33.jar /home/wso2carbon/wso2am-4.6.0/repository/components/lib/mysql-connector-j-8.0.33.jar
